[project]
name = "psychoacoustic-parameter-estimation-via-ml"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "librosa>=1.0.0",
    "matplotlib>=3.11.1",
    "mosqito>=1.2.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pydub>=0.25.1",
    "pyloudnorm>=0.2.0",
    "scipy>=1.18.1",
    "sounddevice>=0.5.6",
    "soundfile>=0.14.0",
    "torch==2.4.1",
    "torch-directml>=0.2.5.dev240914",
]
